# Generated by Django 4.2.6 on 2023-10-27 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in this format: '+country_code-area_number-telephone_number'.", regex='"^\\\\+?[1-9][0-9]{7,14}$"')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'administer'), ('suscriber', 'suscriber'), ('publisher', 'publisher')], default='suscriber', max_length=20),
        ),
    ]
